- contributor_iri: https://orcid.org/0000-0002-0596-5376
  contributor_literal: Quentin Groom
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Botanic Garden Meise
  affiliation_uri: http://www.wikidata.org/entity/Q3052500

- contributor_iri: https://orcid.org/0000-0002-8442-8025
  contributor_literal: Peter Desmet
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  affiliation_uri: http://www.wikidata.org/entity/Q7315097

- contributor_iri: https://orcid.org/0000-0001-7484-9267
  contributor_literal: Lien Reyserhove
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  affiliation_uri: http://www.wikidata.org/entity/Q7315097

- contributor_iri: https://orcid.org/0000-0001-7268-4200
  contributor_literal: Tim Adriaens
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  affiliation_uri: http://www.wikidata.org/entity/Q7315097

- contributor_iri: https://orcid.org/0000-0003-3445-7562
  contributor_literal: Damiano Oldoni
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  affiliation_uri: http://www.wikidata.org/entity/Q7315097

- contributor_iri: https://orcid.org/0000-0002-6298-5373
  contributor_literal: Sonia Vanderhoeven
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Belgian Biodiversity Platform
  affiliation_uri: http://www.wikidata.org/entity/Q100600896

- contributor_iri: https://orcid.org/0000-0003-4365-3135
  contributor_literal: Steven J Baskauf
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Vanderbilt University Libraries
  affiliation_uri: http://www.wikidata.org/entity/Q16849893

- contributor_iri: https://orcid.org/0000-0003-1700-6962
  contributor_literal: Arthur Chapman
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Australian Biodiversity Information Services
  affiliation_uri: http://www.wikidata.org/entity/Q100600913

- contributor_iri: https://orcid.org/0000-0003-3388-2241
  contributor_literal: Melodie McGeoch
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: McGeoch Research Group
  affiliation_uri: http://www.wikidata.org/entity/Q100600923

- contributor_iri: https://orcid.org/0000-0001-8815-0078
  contributor_literal: Ramona Walls
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Arizona
  affiliation_uri: http://www.wikidata.org/entity/Q503419

- contributor_iri: https://orcid.org/0000-0003-1144-0290
  contributor_literal: John Wieczorek
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: VertNet
  affiliation_uri: http://www.wikidata.org/entity/Q98382028

- contributor_iri: https://orcid.org/0000-0003-0174-3239
  contributor_literal: John R.U. Wilson
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: South African National Biodiversity Institute
  affiliation_uri: http://www.wikidata.org/entity/Q30296386

- contributor_iri: https://orcid.org/0000-0002-6056-5084
  contributor_literal: Paula F Zermoglio
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: VertNet
  affiliation_uri: http://www.wikidata.org/entity/Q98382028

- contributor_iri: https://orcid.org/0000-0001-8338-5134
  contributor_literal: Annie Simpson
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: U.S. Geological Survey
  affiliation_uri: http://www.wikidata.org/entity/Q193755
