files:
  - source: /**/*.en.csv
    translation: /**/%file_name%.%locale%.csv
    translation_replace:
      .en.: .
    languages_mapping:
      locale:
        ar: ar
        da: da
        de-DE: de
        es-ES: es
        fr: fr
        ja: ja
        nl-NL: nl
        pt-PT: pt
        ru: ru
        uk: uk
        zh-CN: zh-Hans
        zh-TW: zh-Hant
