# To use this configuration file, it must be in the process directory from which the
# process.py script is run. Typically, a copy is stored with the modifications CSV file.

# Date assigned to all versions, usually the date of approval by the Executive Committee.
# It is appended to all version IRIs. Format: YYYY-MM-DD
date_issued: '2025-07-10'

# UTC offset for the computer running the script (i.e. the appropriate offset for values produced by the
# Python method datetime.datime.now() .
local_offset_from_utc: -05:00

# Only relevant when new term lists or vocabularies are created. It does nothing when
# existing terms are changed. 
# Technical note: this controls which template column mapping file from the "current terms" and "versions"
# directories of the process directory in rs.tdwg.org repo. If additional properties are added in addition
# to the standard ones, the template file will need to be edited. See Section 3 of process-vocaulary.md for details.
# Categories:
# 1: Simple vocabulary
# 2: Simple controlled vocabulary
# 3: Controlled vocabulary with broader hierarchy
vocab_type: 1

# Permanent IRI for the list of terms document that is associated with this vocabulary.
# This is needed to automatically update the date_modified value of the list of terms document 
# using the date_issued value above.
list_of_terms_iri: http://rs.tdwg.org/dwc/doc/list/

# IRI of containing standard. Existing standards IRIs:
# Darwin Core - http://www.tdwg.org/standards/450
# Audiovisual Core - http://www.tdwg.org/standards/638
# Latimer Core - http://www.tdwg.org/standards/x
standard: http://www.tdwg.org/standards/450

# Text to describe the Executive Committee Decision that approved the change.
decisions_text: Namespace errata in Darwin Core main vocabulary corrected by Darwin Core Maintenance Group. See https://github.com/tdwg/dwc/issues/559

namespaces:

# Repeat the following data for each namespace

# For existing term lists, MUST be namespace assigned by issuing organization. For TDWG
# term lists, MUST follow conventional TDWG IRI patterns.
- namespace_uri: http://rs.tdwg.org/dwc/iri/

  # Standard namespace abbreviation for the namespace IRI.
  pref_namespace_prefix: dwciri

  # Database name for associated directories and files. MUST NOT contain spaces. SHOULD use
  # lowerCamelCase. Borrowed term lists SHOULD use naming convention of Darwin and Audiovisual Cores.
  database: iri

  # Set to true if namespace not issued by TDWG and in the rs.tdwg.org domain
  # or if the terms are borrowed from another TDWG standard. 
  # Set to false if namespace issued by TDWG and not borrowed from another standard.
  borrowed: false

  # MUST be set to true if it is a new term list that has never been processed before. 
  # Note that there are extra configuration files that must be set up for term lists that are 
  # part of new vocabularies. See Section 2.1.2 for details. 
  # MUST be set to false if this is an existing term list that has been processed at some time in the past.
  new_term_list: false

  # Normally set to false except for non-versioned namespaces like decisions.
  utility_namespace: false

  # Path to hand-edited changes CSV file. Relative to process directory from which the
  # process.py script is run.
  modifications_file_path: dwc-revisions/dwc-revisions-2025-07-10/iri_2025-07-10.csv

  # For non-borrowed terms where this is the defining term list, SHOULD be the empty string and the termlist 
  # IRI will be set to be the same as the namespace IRI. If a value is given for TDWG-minted terms that are being
  # minted here, it MUST be the same as the namespace IRI (but better to just leave it blank). 
  # When terms are borrowed from other vocabularies (TDWG or outside TDWG) to be included within a
  # vocabulary, an IRI for the borrowed term list conforming to the term list IRI pattern 
  # (https://github.com/tdwg/rs.tdwg.org#3rd-level-iris-denoting-term-lists) MUST be minted. 
  # The subdomain MUST be `rs.tdwg.org` and the first level IRI component following the subdomain MUST be 
  # the standard component for the vocabulary that is borrowing the terms. The second level IRI component 
  # SHOULD be a short, memorable string commonly associated with the borrowed vocabulary. Examples:
  # http://rs.tdwg.org/ac/xmp/ for the XMP terms borrowed by the Audiovisual Core
  # http://rs.tdwg.org/dwc/dcterms/ for the Dublin Core dcterms: terms borrowed by the Darwin Core
  termlist_uri: ''

  # Label used for the term list in machine-readable metadata.
  label: Darwin Core IRI-value Term Analogs

  # Description of the term list used in machine-readable metadata.
  description: The terms on this list are intended to be used with IRI values.
  
  # The following values are used to set up redirects to the list of terms document.

  # IRI string from List of Terms document URL to be prepended to the term fragment identifier when 
  # dereferencing terms and an HTML representation is requested. 
  prepend_url: https://dwc.tdwg.org/list/#

  # Indicates whether the namespace abbreviation is included in the fragment identifier for the term.
  use_namespace_in_fragment: true

  # String that us used to separate the namespace abbreviation from the term name in the fragment identifier.
  # If use_nameapace_in_fragment is false, this value is ignored.
  separator: '_' 
