- contributor_iri: https://orcid.org/0000-0003-1144-0290
  contributor_literal: John Wieczorek
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: VertNet
  affiliation_uri: http://www.wikidata.org/entity/Q98382028

- contributor_iri: https://orcid.org/0000-0002-9284-8871
  contributor_literal: Laura Brenskelle
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0001-6682-1504
  contributor_literal: Robert Guralnick
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0002-4031-1968
  contributor_literal: Kitty Emery
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0002-1741-9997
  contributor_literal: Michelle LeFebvre
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0003-4740-286X
  contributor_literal: Neill Wallis
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Florida
  affiliation_uri: http://www.wikidata.org/entity/Q501758

- contributor_iri: https://orcid.org/0000-0003-4365-3135
  contributor_literal: Steven J Baskauf
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Vanderbilt University Libraries
  affiliation_uri: http://www.wikidata.org/entity/Q16849893

- contributor_iri: https://orcid.org/0000-0002-8481-9034
  contributor_literal: Marie Elise Lecoq
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: GBIF France
  affiliation_uri: https://www.wikidata.org/wiki/Q1531570

- contributor_iri: https://orcid.org/0000-0001-5620-4764
  contributor_literal: Eric Kansa
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Harvard University
  affiliation_uri: http://www.wikidata.org/entity/Q13371

- contributor_iri: https://orcid.org/0000-0001-7920-5321
  contributor_literal: Sarah Kansa
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: The Alexandria Archive Institute
  affiliation_uri: https://www.wikidata.org/wiki/Q30257865

- contributor_iri: https://orcid.org/0000-0001-9325-3100
  contributor_literal: Denné Reed
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: University of Texas at Austin
  affiliation_uri: https://www.wikidata.org/wiki/Q49213
