- contributor_iri: https://orcid.org/0000-0003-4365-3135
  contributor_literal: Steven J Baskauf
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Vanderbilt University Heard Libraries
  affiliation_uri: http://www.wikidata.org/entity/Q16849893

- contributor_iri: https://orcid.org/0000-0002-5887-9543
  contributor_literal: Edward Baker
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Natural History Museum, London
  affiliation_uri: http://www.wikidata.org/entity/Q309388

- contributor_iri: https://orcid.org/0000-0001-8068-3769
  contributor_literal: Dan Stowell
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Queen Mary University of London
  affiliation_uri: http://www.wikidata.org/entity/Q195668

- contributor_iri: https://orcid.org/0000-0003-2224-6821
  contributor_literal: Niels Klazenga
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Royal Botanic Gardens Victoria
  affiliation_uri: http://www.wikidata.org/entity/Q7373836
