- contributor_iri: https://orcid.org/0000-0003-2224-6821
  contributor_literal: Niels Klazenga
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Royal Botanic Gardens Victoria, Australia/Atlas of Living Australia, Australia
  affiliation_uri: http://www.wikidata.org/entity/Q7373836

- contributor_iri: https://orcid.org/0000-0002-2954-9027
  contributor_literal: Greg Whitbread
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Taxamatics, Australia
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0000-0002-4852-2567
  contributor_literal: Vijay Barve
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Natural History Museum of Los Angeles County, USA
  affiliation_uri: http://www.wikidata.org/entity/Q2502709

- contributor_iri: https://orcid.org/0000-0001-9277-2478
  contributor_literal: Thierry Bourgoin
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Museum national histoire naturelle Paris, France
  affiliation_uri: http://www.wikidata.org/entity/Q838691

- contributor_iri: https://orcid.org/0000-0001-7757-1889
  contributor_literal: Markus Döring
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: GBIF, Denmark/Catalogue of Life, The Netherlands
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: https://orcid.org/0000-0001-5737-8803
  contributor_literal: Anne Fuchs
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Centre for Australian National Biodiversity Research, Australia
  affiliation_uri: http://www.wikidata.org/entity/Q30264210

- contributor_iri: https://orcid.org/0000-0003-0551-5989
  contributor_literal: Jeff Gerbracht
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Cornell Lab of Ornithology, USA
  affiliation_uri: http://www.wikidata.org/entity/Q2997535

- contributor_iri: https://orcid.org/0000-0003-0442-8162
  contributor_literal: Johan Liljeblad
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Swedish Species Information Centre, Sweden
  affiliation_uri: http://www.wikidata.org/entity/Q16497181

- contributor_iri: https://orcid.org/0000-0002-6740-2122
  contributor_literal: Carlos Martínez Muñoz
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: ''
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0009-0004-5278-4238
  contributor_literal: Mieke Strong
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Gaia Resources, Australia
  affiliation_uri: ''

- contributor_iri: https://orcid.org/0000-0003-2863-2491
  contributor_literal: William Ulate
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Missouri Botanical Garden, USA
  affiliation_uri: http://www.wikidata.org/entity/Q1852803

- contributor_iri: https://orcid.org/0000-0003-1031-3249
  contributor_literal: Cam Webb
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: University of Alaska Museum of the North, USA
  affiliation_uri: http://www.wikidata.org/entity/Q7895036
