
- contributor_literal: Elspeth Haston
  contributor_iri: https://orcid.org/0000-0001-9144-2848
  affiliation: Royal Botanic Garden Edinburgh, UK

- contributor_literal: Cat Chapman
  contributor_iri: https://orcid.org/0000-0002-0681-2515
  affiliation: Northern Arizona University & iDigBio, USA

- contributor_literal: Alex Hardisty
  contributor_iri: Cardiff University
  affiliation: Wouter Addink (Naturalis, NL

- contributor_literal: Mathias Dillen
  contributor_iri: https://orcid.org/0000-0002-3973-1252
  affiliation: Meise Botanic Garden, BE

- contributor_literal: Quentin Groom
  contributor_iri: Meise Botanic Garden, BE
  affiliation: Falko Glöckler (Museum für Naturkunde Berlin, DE

- contributor_literal: Deborah Paul
  contributor_iri: iDigBio, USA
  affiliation: Mareike Petersen (Museum für Naturkunde Berlin, DE

- contributor_literal: Hannu Saarenmaa
  contributor_iri: Bioshare Digitization, FI
  affiliation: Anton Güntsch (Botanic Garden and Botanical Museum Berlin, DE

- contributor_literal: Ben Norton

- contributor_literal: Anke Penzlin
  contributor_iri: https://orcid.org/0000-0003-2183-893X
  affiliation: Senckenberg – Leibniz Institution for Biodiversity and Earth System Research)

- contributor_literal: Claus Weiland
  contributor_iri: https://orcid.org/0000-0003-0351-6523
  affiliation: Senckenberg – Leibniz Institution for Biodiversity and Earth System Research

- contributor_literal: Eirik Rindal
  contributor_iri: https://orcid.org/0000-0003-1568-6386
  affiliation: Natural History Museum, University of Oslo

- contributor_literal: Dagmar Triebel
  contributor_iri: https://orcid.org/0000-0003-1980-3148
  affiliation: Bavarian Natural History Collections

- contributor_literal: Rachel Walcott
  contributor_iri: https://orcid.org/0000-0002-0488-6393
  affiliation: National Museums Scotland

- contributor_literal: Donat Agosti
  contributor_iri: https://orcid.org/0000-0001-9286-1200
  affiliation: Plazi

- contributor_literal: Felipe Simoes
  contributor_iri: https://orcid.org/0000-0002-1218-2839
  affiliation: Plazi

- contributor_literal: Josh Humphries
  contributor_iri: https://orcid.org/0000-0001-5493-9804
  affiliation: Natural History Museum, London
