# ----------------
# Values set by the task group or maintainers of the standard.
# ----------------

# Official title of the document assigned by authors.
documentTitle: "Humboldt Extension Vocabulary List of Terms"

# Abstract of document written by authors.
abstract: The Humboldt Extension for Ecological Inventories provides a standardized vocabulary to 
  report key information about biodiversity inventories, checklists and surveys, maximizing the 
  usability and interoperability 
  of these data. This vocabulary is employed along with the Darwin Core (DwC) terms, effectively 
  broadening the scope of dwc:Event records by incorporating terms absent from the main DwC vocabulary. 
  Terms included in the extension are defined such that they can accommodate hierarchical data 
  structures allowing the representation of complex, highly nested survey designs, permitting the 
  computation of relative abundances of species. This document 
  lists all terms currently used in the vocabulary providing comments and examples of their usage 
  along with ancillary documents that provide guidance on the use and interpretation of terms and 
  the data structure needed to accommodate dwc:Event hierarchies frequently observed in ecological 
  inventories.

# This value is generally the name of the task group that created the document.
creator: TDWG Humboldt Extension Task Group

# Current (2023-08-27) practice is to publish documents as Markdown files in a TDWG GitHub repository.
# These Markdown documents are then converted to HTML by GitHub Pages. To match the TDWG theme, the 
# document maintainers will need to work with the Infrastructure team to set up the repository so 
# that it can host the ancillary website for the standard or vocabulary. 
# The exact setup of the repository will determin the values of accessUrl and browserRedirectUri.

# Media type of source document used to generate the HTML version of the document.
mediaType: text/markdown

# Value determined by the location of the raw Markdown file in the GitHub repository.
# The repository pattern used should be to create a subdirectory for the document whose name will be
# the slug for the page, then place the Markdown file named index.md in that subdirectory.
accessUrl: https://raw.githubusercontent.com/tdwg/hc/main/docs/list/index.md

# Actual URL of the document to which the permanent IRI is redirected.
# When generated by GitHub pages, this will be related to the location of the raw Markdown file.
# The initial default value is https://tdwg.github.io/repository_name/subdirectory_name/.
# However, typically, the Infrastructure team sets up a subdomain of the tdwg.org domain for the
# ancillary website. In that case, the value will eventually be 
# https://subdomain.tdwg.org/subdirectory_name/.
browserRedirectUri: https://eco.tdwg.org/list/

# ----------------
# Values set by the TDWG Infrastructure team at time of ratification
# ----------------

# Permanent IRI of the standard with which the document is associated. 
# For documents added to an existing standard, see the landing page
# for the standard on the TDWG website for the correct value.
# For new standards, this value will be set by the TDWG Infrastructure team.
dcterms_isPartOf: http://www.tdwg.org/standards/450

# IRI value assigned as a permanent identifier for the document based on standard TDWG IRI patterns.
# This value will automatically get updated from the general_configuration.yaml file. It should not be
# set manually.
current_iri: http://rs.tdwg.org/dwc/doc/eco/

# Date of first ratification of the document. Will match the doc_modified value for the first
# version of the document. For lists of terms, this will also match the date that the
# first version of the vocabulary was issued (date_issued).
doc_created: '2024-02-28'

# ----------------
# Do not edit below this line
# ----------------

# Standard metadata determined by TDWG policy.
publisher: Biodiversity Information Standards (TDWG)
license_statement: Licensed under a Creative Commons Attribution 4.0 International (CC BY) License.
license_uri: http://creativecommons.org/licenses/by/4.0/

# Typically left blank. May be used to provide additional information about the document
# in the machine-readable metadata.
comment: ''

# This value will automatically get updated from the date_issued value in config.yaml if the document
# is a list of terms document. For other types of documents, it is set from the general_configuration.yaml
# file.
doc_modified: '2025-07-10'
